/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exam1;
import java.util.*;

/**
 * Runs UnderOver GUI
 * @author Kat
 */
public class GUIgame extends javax.swing.JFrame {

   ArrayList <String> userTrack = new ArrayList <String>();
    
    /**
     * Creates new form GUIgame
     */
    public GUIgame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        Roll = new javax.swing.JButton();
        MoneyLabel = new javax.swing.JLabel();
        Money = new javax.swing.JLabel();
        BetLabel = new javax.swing.JLabel();
        Bet_TF = new javax.swing.JTextField();
        Title = new javax.swing.JLabel();
        UserLabel = new javax.swing.JLabel();
        DiceLabel = new javax.swing.JLabel();
        User_TF = new javax.swing.JTextField();
        Under7 = new javax.swing.JRadioButton();
        Over7 = new javax.swing.JRadioButton();
        Seven = new javax.swing.JRadioButton();
        Submit = new javax.swing.JButton();
        winlose = new javax.swing.JLabel();

        jDialog1.setResizable(false);
        jDialog1.setSize(new java.awt.Dimension(150, 100));

        jLabel1.setText("Bet must be an integer!");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Roll.setText("Roll Dice!");
        Roll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RollActionPerformed(evt);
            }
        });

        MoneyLabel.setText("Money: $");

        Money.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Money.setText("--");

        BetLabel.setText("Bet: $");

        Title.setFont(new java.awt.Font("Bodoni 72 Smallcaps", 1, 24)); // NOI18N
        Title.setText("Over-Under");

        UserLabel.setText("Please Log In with your username below:");

        DiceLabel.setFont(new java.awt.Font("Lucida Grande", 1, 48)); // NOI18N
        DiceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DiceLabel.setText("--");

        User_TF.setText("Enter Username");

        Under7.setText("Under 7");
        Under7.setToolTipText("");
        Under7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Under7ActionPerformed(evt);
            }
        });

        Over7.setText("Over 7");
        Over7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Over7ActionPerformed(evt);
            }
        });

        Seven.setText("7");
        Seven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SevenActionPerformed(evt);
            }
        });

        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        winlose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        winlose.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(UserLabel)
                .addGap(46, 46, 46))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(Title))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(winlose, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DiceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Roll, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(Under7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Seven)
                .addGap(18, 18, 18)
                .addComponent(Over7)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(MoneyLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Money, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(BetLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Bet_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(User_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Submit)))
                .addGap(71, 71, 71))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UserLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(User_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Submit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MoneyLabel)
                    .addComponent(Money)
                    .addComponent(BetLabel)
                    .addComponent(Bet_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Under7)
                    .addComponent(Over7)
                    .addComponent(Seven))
                .addGap(40, 40, 40)
                .addComponent(DiceLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(winlose)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(Roll)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * When the "Roll Dice!" button is pushed, a dice sum and win/lose prompt is shown; 
     * The total money is adjusted depending on which radio button is selected and value of the bet.
     * @param evt 
     */
    private void RollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RollActionPerformed
        // TODO add your handling code here:
        try {
            UnderOver.rollDice();
            String s = String.valueOf(UnderOver.rollDice());
            DiceLabel.setText(s);

            if(Under7.isEnabled()) {
                int c = Integer.parseInt(this.Bet_TF.getText());
                String f = String.valueOf(UnderOver.underSeven(c));
                Money.setText(f);
                if(Integer.parseInt(s) < 7)
                    winlose.setText("You Win!");
                else
                    winlose.setText("You Lose!");

            } else if(Seven.isEnabled()) {
                int c = Integer.parseInt(this.Bet_TF.getText());
                String f = String.valueOf(UnderOver.seven(c));
                Money.setText(f);
                if(Integer.parseInt(s) == 7)
                    winlose.setText("You Win!");
                else
                    winlose.setText("You Lose!");

            } else {
                int c = Integer.parseInt(this.Bet_TF.getText());
                String f = String.valueOf(UnderOver.overSeven(c));
                Money.setText(f);
                if(Integer.parseInt(s) > 7)
                    winlose.setText("You Win!");
                else
                    winlose.setText("You Lose!");
            }
        } catch(NumberFormatException ex) {
            jDialog1.show();
            }
    }//GEN-LAST:event_RollActionPerformed

    /**
     * When "Submit" button is pushed, the username given in the text field is 
     * added to a list.
     * @param evt 
     */
    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        // TODO add your handling code here:
        userTrack.add(User_TF.getText());
        String s = String.valueOf(UnderOver.setNewMoney());
        Money.setText(s);
    }//GEN-LAST:event_SubmitActionPerformed

    /**
     * Tells program that the "Under 7" radio button is selected. 
     * @param evt 
     */
    private void Under7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Under7ActionPerformed
        // TODO add your handling code here:
        Under7.enable(true);
        Seven.enable(false);
        Over7.enable(false);
    }//GEN-LAST:event_Under7ActionPerformed
    
    /**
     * Tells program that the "7" radio button is selected.
     * @param evt 
     */
    private void SevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SevenActionPerformed
        // TODO add your handling code here:
        Seven.enable(true);
        Under7.enable(false);
        Over7.enable(false);
    }//GEN-LAST:event_SevenActionPerformed

    /**
     * Tells program that the "Over 7" radio button is selected.
     * @param evt 
     */
    private void Over7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Over7ActionPerformed
        // TODO add your handling code here:
        Over7.enable(true);
        Under7.enable(false);
        Seven.enable(false);
    }//GEN-LAST:event_Over7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIgame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIgame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIgame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIgame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIgame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BetLabel;
    private javax.swing.JTextField Bet_TF;
    private javax.swing.JLabel DiceLabel;
    private javax.swing.JLabel Money;
    private javax.swing.JLabel MoneyLabel;
    private javax.swing.JRadioButton Over7;
    private javax.swing.JButton Roll;
    private javax.swing.JRadioButton Seven;
    private javax.swing.JButton Submit;
    private javax.swing.JLabel Title;
    private javax.swing.JRadioButton Under7;
    private javax.swing.JLabel UserLabel;
    private javax.swing.JTextField User_TF;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel winlose;
    // End of variables declaration//GEN-END:variables
}
